# Copyright 2016 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ARG_FROM

MAINTAINER Krishnath Poologanathan <pkrishnath@gmail.com>

ENV VERSION v2.2.3
ENV FILENAME helm-${VERSION}-linux-amd64.tar.gz

RUN apk add --no-cache ca-certificates bash



ADD http://storage.googleapis.com/kubernetes-helm/${FILENAME} /tmp

RUN tar -zxvf /tmp/${FILENAME} -C /tmp \
  && mv /tmp/linux-amd64/helm /bin/helm \
  && rm -rf /tmp
  
ADD bin/ARG_ARCH/ARG_BIN /ARG_BIN



ENTRYPOINT ["/ARG_BIN"]

